name: emcall
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.1.2
  slider_button: ^2.1.0
  intl_phone_field: ^3.2.0
  intl: ^0.19.0
  camera: ^0.11.0+2
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/your_image.png
